# Load bronze to silver

In [2]:
import os
import pandas as pd

## Parametros

In [3]:
bronze_path = os.path.join(
    os.curdir, "Data_Lake", "Bronze"
)
silver_path = os.path.join(
    os.curdir, "Data_Lake", "Silver"
)

In [4]:
bronze_file_name = "menstrual_cycle_bronze.parquet"

silver_file_name = "menstrual_cycle__silver.parquet"

In [5]:
bronze_file_path = os.path.join(
    bronze_path, bronze_file_name
)
silver_file_path = os.path.join(
    silver_path, silver_file_name
)

## Main

### Cargar los de datos de Bronze

In [7]:
bronze_menstrual_cycle_df = pd.read_parquet(bronze_file_path)

In [8]:
bronze_menstrual_cycle_df.head()

,User ID,Age,BMI,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,_BronzeTimestamp
0,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,26,7.0,52:34.9,Headache,2025-11-06 17:24:13.627513
1,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,32,5.0,52:34.9,Fatigue,2025-11-06 17:24:13.627513
2,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,41,7.0,52:34.9,Fatigue,2025-11-06 17:24:13.627513
3,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,27,3.0,52:34.9,Fatigue,2025-11-06 17:24:13.627513
4,1.0,18,29.28,2,Moderate,5.4,Low Carb,52:34.9,42,5.0,52:34.9,Cramps,2025-11-06 17:24:13.627513

### Normalización de datos

#### Nulos

In [11]:
bronze_menstrual_cycle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User ID                892 non-null    float64
 1   Age                    895 non-null    int64
 2   BMI                    895 non-null    float64
 3   Stress Level           895 non-null    int64
 4   Exercise Frequency     895 non-null    object
 5   Sleep Hours            895 non-null    float64
 6   Diet                   895 non-null    object
 7   Cycle Start Date       895 non-null    object
 8   Cycle Length           895 non-null    int64
 9   Period Length          888 non-null    float64
 10  Next Cycle Start Date  892 non-null    object
 11  Symptoms               888 non-null    object
 12  _BronzeTimestamp       895 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(3), object(5)
memory usage: 91.0+ KB

In [ ]:
# LA columna User ID es una columna critica. 
# El analisis se basa en el ciclo mesntrual completo de una persona => 11 repeticiones del mismo User ID coincidien

#
bronze_menstrual_cycle_df[bronze_menstrual_cycle_df['User ID'].isnull() == True]

,User ID,Age,BMI,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,_BronzeTimestamp
94,NaN,33,22.99,3,High,7.1,Vegetarian,52:34.9,37,6.0,52:34.9,Headache,2025-11-06 17:24:13.627513
100,NaN,20,28.33,5,Low,5.8,High Sugar,52:34.9,28,3.0,52:34.9,Bloating,2025-11-06 17:24:13.627513
103,NaN,20,28.33,5,Low,5.8,High Sugar,52:34.9,27,4.0,52:34.9,Headache,2025-11-06 17:24:13.627513