# Load bronze to silver

In [1]:
import os
import pandas as pd

## Parametros

In [2]:
bronze_path = os.path.join(
    os.curdir, "Data_Lake", "Bronze"
)
silver_path = os.path.join(
    os.curdir, "Data_Lake", "Silver"
)

In [3]:
bronze_file_name = "menstrual_cycle_bronze.parquet"

silver_file_name = "menstrual_cycle__silver.parquet"

In [4]:
bronze_file_path = os.path.join(
    bronze_path, bronze_file_name
)
silver_file_path = os.path.join(
    silver_path, silver_file_name
)

## Main

### Cargar los de datos de Bronze

In [5]:
bronze_menstrual_cycle_df = pd.read_parquet(bronze_file_path)

In [6]:
bronze_menstrual_cycle_df.head()

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
0,1.0,18.0,2.0,Moderate,54.0,Low Carb,13/11/2024 20:52,26,7.0,09/12/2024 20:52,Headache,29.28,2025-11-06 19:16:40.445350
1,1.0,18.0,2.0,Moderate,54.0,Low Carb,09/12/2024 20:52,32,5.0,10/01/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
2,1.0,18.0,2.0,Moderate,54.0,Low Carb,10/01/2025 20:52,41,7.0,20/02/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
3,1.0,18.0,2.0,Moderate,54.0,Low Carb,20/02/2025 20:52,27,3.0,19/03/2025 20:52,Fatigue,29.28,2025-11-06 19:16:40.445350
4,1.0,18.0,2.0,Moderate,54.0,Low Carb,19/03/2025 20:52,42,5.0,30/04/2025 20:52,Cramps,29.28,2025-11-06 19:16:40.445350

### Normalización de datos

#### Nulos

In [7]:
bronze_menstrual_cycle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 895 entries, 0 to 894
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User ID                893 non-null    float64
 1   Age                    892 non-null    float64
 2   Stress Level           893 non-null    float64
 3   Exercise Frequency     894 non-null    object
 4   Sleep Hours            893 non-null    float64
 5   Diet                   895 non-null    object
 6   Cycle Start Date       895 non-null    object
 7   Cycle Length           895 non-null    int64
 8   Period Length          892 non-null    float64
 9   Next Cycle Start Date  895 non-null    object
 10  Symptoms               895 non-null    object
 11  BMI                    895 non-null    float64
 12  _BronzeTimestamp       895 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(6), int64(1), object(5)
memory usage: 91.0+ KB

In [ ]:
# Edades asociadas a cada usuario
with pd.option_context('display.max_rows',None,'display.max_columns',None):
    print(bronze_menstrual_cycle_df.groupby('User ID')['Age'].unique())

User ID
1.0                  [18.0]
2.0                  [34.0]
3.0                  [22.0]
4.0                  [25.0]
5.0                  [25.0]
6.0                  [44.0]
7.0                  [75.0]
8.0                  [37.0]
9.0                  [24.0]
10.0                 [33.0]
11.0                 [20.0]
12.0                 [29.0]
13.0                 [35.0]
14.0                 [26.0]
15.0                 [39.0]
16.0                 [23.0]
17.0                [140.0]
18.0                 [20.0]
19.0            [21.0, nan]
20.0            [45.0, nan]
21.0                 [19.0]
22.0                 [33.0]
23.0                 [44.0]
24.0                 [19.0]
25.0                 [26.0]
26.0                 [28.0]
27.0                 [45.0]
28.0                 [19.0]
29.0     [27.0, 38.0, 37.0]
31.0                 [37.0]
32.0                 [25.0]
33.0                 [44.0]
34.0                 [32.0]
35.0                 [29.0]
36.0                 [31.0]
37.0                 [44.0]
38.0                 [45.0]
39.0                 [23.0]
40.0                 [18.0]
41.0                 [33.0]
42.0                 [24.0]
43.0                 [28.0]
44.0                 [26.0]
45.0                 [21.0]
46.0                 [25.0]
47.0                 [25.0]
48.0                 [42.0]
49.0                 [35.0]
50.0                 [38.0]
51.0                 [35.0]
52.0                 [26.0]
53.0                 [43.0]
54.0                 [26.0]
55.0                 [31.0]
56.0                 [31.0]
57.0                 [39.0]
58.0                 [39.0]
59.0                 [30.0]
60.0                 [39.0]
61.0                 [33.0]
62.0                 [40.0]
63.0                 [21.0]
64.0                 [22.0]
65.0                 [41.0]
66.0                 [20.0]
67.0                 [25.0]
68.0                 [44.0]
69.0                 [31.0]
70.0                 [34.0]
71.0                 [34.0]
72.0                 [38.0]
73.0                 [45.0]
74.0                 [34.0]
75.0                 [27.0]
76.0                 [40.0]
77.0                 [28.0]
78.0                 [37.0]
79.0                 [22.0]
80.0                 [35.0]
81.0                 [36.0]
82.0                 [42.0]
83.0                 [25.0]
84.0                 [40.0]
85.0                 [45.0]
86.0                 [36.0]
87.0                 [44.0]
88.0                 [18.0]
89.0                 [20.0]
90.0                 [30.0]
91.0                 [32.0]
92.0                 [29.0]
93.0                 [21.0]
94.0                 [20.0]
95.0                 [27.0]
96.0                 [44.0]
97.0                 [37.0]
98.0                 [19.0]
99.0                 [39.0]
100.0                [22.0]
Name: Age, dtype: object

In [ ]:
# Un usuario puede tener 2 edades asociadas ya que depende de la duración de su registro de ciclos.
# Sin embargo las edades tienen que guardar linealidad.

In [25]:
# No existe una columna critica única.
bronze_menstrual_cycle_df[bronze_menstrual_cycle_df['User ID'].isnull() == True]

,User ID,Age,Stress Level,Exercise Frequency,Sleep Hours,Diet,Cycle Start Date,Cycle Length,Period Length,Next Cycle Start Date,Symptoms,BMI,_BronzeTimestamp
173,NaN,21.0,1.0,Low,80.0,Balanced,28/01/2025 20:52,33,7.0,02/03/2025 20:52,Headache,21.57,2025-11-06 19:16:40.445350
182,NaN,45.0,4.0,Low,75.0,Low Carb,29/03/2024 20:52,39,3.0,07/05/2024 20:52,Cramps,24.82,2025-11-06 19:16:40.445350